
package cl.clarochile.webservices.userpermission;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cl.clarochile.webservices.types.PaginationType;
import cl.clarochile.webservices.types.UserPermissionType;
import cl.clarochile.webservices.types.WebserviceStatusType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserPermission", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/")
@XmlSeeAlso({
    cl.clarochile.webservices.types.ObjectFactory.class,
    cl.clarochile.webservices.userpermission.ObjectFactory.class
})
public interface UserPermission {


    /**
     * 
     * @param userPermission
     * @return
     *     returns cl.clarochile.webservices.types.WebserviceStatusType
     */
    @WebMethod(operationName = "CreateUserPermission", action = "http://www.clarochile.cl/webservices/UserPermission/CreateUserPermission")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "CreateUserPermission", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.CreateUserPermission")
    @ResponseWrapper(localName = "CreateUserPermissionResponse", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.CreateUserPermissionResponse")
    public WebserviceStatusType createUserPermission(
        @WebParam(name = "userPermission", targetNamespace = "")
        UserPermissionType userPermission);

    /**
     * 
     * @param userPermission
     * @return
     *     returns cl.clarochile.webservices.types.WebserviceStatusType
     */
    @WebMethod(operationName = "UpdateUserPermission", action = "http://www.clarochile.cl/webservices/UserPermission/UpdateUserPermission")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "UpdateUserPermission", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.UpdateUserPermission")
    @ResponseWrapper(localName = "UpdateUserPermissionResponse", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.UpdateUserPermissionResponse")
    public WebserviceStatusType updateUserPermission(
        @WebParam(name = "userPermission", targetNamespace = "")
        UserPermissionType userPermission);

    /**
     * 
     * @param userPermission
     * @return
     *     returns cl.clarochile.webservices.types.WebserviceStatusType
     */
    @WebMethod(operationName = "DeleteUserPermission", action = "http://www.clarochile.cl/webservices/UserPermission/DeleteUserPermission")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "DeleteUserPermission", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.DeleteUserPermission")
    @ResponseWrapper(localName = "DeleteUserPermissionResponse", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.DeleteUserPermissionResponse")
    public WebserviceStatusType deleteUserPermission(
        @WebParam(name = "userPermission", targetNamespace = "")
        UserPermissionType userPermission);

    /**
     * 
     * @param status
     * @param search
     * @param rut
     * @param list
     * @param rutDelegate
     * @param pagination
     */
    @WebMethod(operationName = "ListUserPermission", action = "http://www.clarochile.cl/webservices/UserPermission/ListUserPermission")
    @RequestWrapper(localName = "ListUserPermission", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.ListUserPermission")
    @ResponseWrapper(localName = "ListUserPermissionResponse", targetNamespace = "http://www.clarochile.cl/webservices/UserPermission/", className = "cl.clarochile.webservices.userpermission.ListUserPermissionResponse")
    public void listUserPermission(
        @WebParam(name = "rut", targetNamespace = "")
        String rut,
        @WebParam(name = "rutDelegate", targetNamespace = "")
        String rutDelegate,
        @WebParam(name = "search", targetNamespace = "")
        String search,
        @WebParam(name = "pagination", targetNamespace = "")
        PaginationType pagination,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<WebserviceStatusType> status,
        @WebParam(name = "list", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<UserPermissionType> list);

}
